### ISSUE TITLE
Similar module here?

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/upgrade_ui#1]
This may be similar: https://github.com/backdrop-contrib/d2b_migrate

**Comment by jenlampton** [comment]
This looks exactly like what I had envisioned ❤️  I'll give it a test (and probably contribute there, rather than here, and maybe delete this project?)

**Comment by jenlampton** [comment]
In testing at BADCamp, everyone loved https://github.com/backdrop-contrib/d2b_migrate, so I'm going to remove this module from the contrib space to prevent people form being confused about which to use. Thank you @docwilmot for seeing the need and solving the problem!
